# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: light
  color: indigo

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: 'Vincenzo Coia Solutions'
    description: 'A data science and statistical research expert specializing in probabilistic modeling, extreme value analysis, and practical solutions for real-world challenges.'
    #twitter: ''
  analytics:
    google_analytics: 'G-057C5TFBSQ'
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    align: "center"
    fixed_to_top: true
    logo:
      text: ""
      # Logo filename in `assets/media/` folder
      filename: "V-logo.png"
    #button:
    #  enable: true
    #  text: "Get Started"
    #  url: "https://hugoblox.com/templates/"
    show_search: true
    show_theme_chooser: true

# Site footer
footer:
  copyright:
    notice: '© {year} Vincenzo Coia'

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
