theme: jekyll-theme-dinky
name: Vincenzo Coia
description: Browse my public files.
footer-links:
  github: vincenzocoia/vincenzocoia.github.io
  linkedin: vincenzocoia
  twitter: vincenzocoia
  stackoverflow: users/8294608/vincenzocoia
