---
title: "Diversity Statement"
subtitle: ""
summary: ""
date: 2019-11-18T23:32:49-08:00
lastmod: 2019-11-18T23:32:49-08:00
featured: false
draft: true
---

**Under Construction**

To me, people deserve the same respect regardless of their identity. Any differential treatment is discrimination, and is problematic because it leaves people feeling disrespected at best, and contributes to the difficulty of one's life at worst. 

Our society has made some great progress on inclusivity (the opposite of discrimination). Racial and sexual discrimination are significantly less these days compared to several decades ago. But the battle is still not over, as is evidenced by graffitied rainbow sidewalks and defaced mosques. 

Some discrimination is still rife. Gender discrimination is one such example, which is now starting to see some progress. But there are still other types of discrimination that are not yet well known. One such example that I feel is happening is discrimination against fathers.  

Not only is it healthy for each individual to receive respectful and equal treatment, we have so much to gain by having a diverse group of people around us. There's strength in diversity.

### My experience with discrimination

As a member of the LGBTQ community, I continue to experience discrimination. Me and my male partner holding hands in public still forms a spectacle to many, some even stopping to watch us after we've walked by. Wedding vendors still refer to a "bride" when mentioning our wedding. Being invited to a wedding under the condition that my partner and I show no affection. Things were worse in my adolescence, where homosexuality was "discouraged" in my environment, leaving me feeling socially out of place and fearful. Luckily, only some extended family members have a problem with my identity, and the rest embrace me.




Women's bathroom at 49th ||. 

Hand-holding

Whistler bathroom

Fatherhood

Wedding

Sticker on office door

Contribution? It's about calling out discrimination.



 

- "Contribution" to the LGBTQ community: my [LGBTSTEM interview](https://lgbtstem.wordpress.com/2019/11/09/an-interview-with-vincenzo-coia/).

The problem goes deeper and more elusive with the well-intentioned people who still discriminate unintentionally:

The problem does not necessarily lie with a discriminative response from an individual, if the response was unintentional. Despite the best of intentions, it's our environment and society that is responsible for crafting an automatic response from an individual. So, a good-intentioned individual that does a double-take after seeing me and my male partner holding hands should not beat themselves up over it -- it just means that the cumulative effect of their environment over time crafted such a response.
