---
title: "CV of Failures"
subtitle: ""
summary: ""
date: 2019-11-18T23:32:49-08:00
lastmod: 2019-11-18T23:32:49-08:00
featured: false
draft: true
---

**Under Construction**

Why this document? It's important to recognize a failure when it happens, as a first step towards learning from the failure. That's what this page is. In addition, I haven't always done this -- there have been times that I've been hesitant to call some failures a failure. I'm hoping this page will help me avoid sugar-coating failures in the future so that I can ["fail better"](https://www.listennotes.com/podcasts/lead-to-win-with/080-how-to-fail-better-0UneBxMHsal/).

This is definitely not an exhaustive list/discussion. In addition to sugar-coating failures, I'm relying on memory.

I've made this page public so that I can hopefully inspire others to take ownership over their failures too, but also to show everyone that I'm human, too. I got the idea from [Mike Gelbart](https://www.mikegelbart.com/), but the idea seems to have originally stemmed from [Melanie Stefan's _Nature_ article](https://www.nature.com/naturejobs/science/articles/10.1038/nj7322-467a).



- No published papers from my PhD
- I never ended up submitting my first two R packages, [`copsupp`]() and [`cnqr`](), to CRAN, because they are a mess and are incomplete.
	- I'm turning this around: I'm nearly finished a new-and-improved paper and analysis, and have new framework for new R packages (see [distplyr]() and [coperate]()).
- Applied to several positions coming out of my PhD to no avail: including Boeing and Amazon.
- Scholarships: I failed to get many, but two notable ones that I was not successful for was the Vanier and CGS-D scholarships (although I did get PGS-D).
- I dropped an oenology and viticulture course in my undergrad because I couldn't handle the workload of six courses, and I failed the midterm exam.
- I struggled to get A's in my biology courses in undergrad.
- I signed up for a half marathon and didn't run it because I failed to adequately prepare.
- Several rejections for submissions to peer reviewed journals.
- I've never won any formal individual fencing competitions in my ~6 years of fencing.
- I once joined a kettlebell gym ($100+), and failed to go even once. 